server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false
  log_level: "info"

model:
  pattern_retrieval:
    embedding_dim: 128
    top_k: 10
    window_size: 20
    forward_periods: 5
    index_type: "HNSW"  # HNSW for scalability, Flat for simplicity
    hnsw_m: 32
    hnsw_ef_search: 128
    hnsw_ef_construction: 200

  market_clip:
    text_encoder: "sentence-transformers/all-MiniLM-L6-v2"
    embedding_dim: 256
    price_input_dim: 10
    learning_rate: 0.0001
    batch_size: 32
    temperature: 0.07

  ensemble:
    n_models: 5
    voting_strategy: "weighted"  # weighted, average, median

mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "market-intelligence"
  artifact_location: "./mlruns"
  model_registry: false

monitoring:
  prometheus:
    enabled: true
    port: 9090
    metrics_path: "/metrics"

  logging:
    level: "INFO"
    format: "json"
    file: "logs/app.log"
    rotation: "500 MB"
    retention: "30 days"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  cache_ttl: 3600  # 1 hour
  max_connections: 50

api:
  rate_limit:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000

  auth:
    enabled: true
    jwt_secret: "${JWT_SECRET}"
    jwt_algorithm: "HS256"
    access_token_expire_minutes: 30

  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:8000"

data:
  news:
    alpha_vantage_key: "${ALPHA_VANTAGE_KEY}"
    yahoo_enabled: true
    cache_enabled: true
    cache_dir: "data/cache/news"

  patterns:
    save_dir: "data/processed/patterns"
    backup_enabled: true
    backup_interval_hours: 24

inference:
  batch_size: 32
  timeout_seconds: 30
  uncertainty_quantification: true
  min_confidence_threshold: 0.5

drift_detection:
  enabled: true
  window_size: 1000
  check_interval_hours: 24
  threshold_psi: 0.1
  threshold_js: 0.1
  retrain_on_drift: true
